""" Admin site configuration for authentication and authrization app

	This module used to register models into default django admin panel.
	It contains custome admin sites and configurations.

	Generated by: python3 manage.py startapp
	Last modified by: Wendirad Demelash
"""

from django.contrib import admin
from django.contrib.auth.models import Group

# Group will be manged dynamicaly not need
# add in admin panel
admin.site.unregister(Group)
