""" Authentication and authorization app configuration
    
    This application configuration file contains list of subclasses of
    'AppConfig' which will be used to configure the entire application.

    This module also used to register signals used in this application.

    Generated by: python3 manage.py startapp
    Last modified by: Wendirad Demelash
"""

from django.apps import AppConfig


class AusersConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "ausers"
