""" List of subclassed of django.db.models.Model for authenticationa and
	authoraization apps.

	The file will include declaration of model which will be used when 
	performing database quiries on views and other parts of the code.

	Generated by: python3 manage.py startapp
	Last modified by: Wendirad Demelash
"""
from django.db import models
