""" List of django views, that represent logical layer of an application

	This file contains all logical layer implementation, include database quiries,
	and template renderings.

	Generated by: python3 manage.py startapp
	Last modified by: Wendirad Demelash
"""
