# Generated by Django 3.2.7 on 2021-10-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(default='', upload_to='Posts/images/'),
            preserve_default=False,
        ),
    ]
